### ISSUE TITLE
RDMP plugin support for IsIdentifiable via the DQE

### ISSUE THREAD

**Issue by tznind** [SMI/SmiServices#1024]
IsIdentifiable is a tool that is useful from core RDMP and so now that we have SmiPlugin it would be nice to implement `IPredictionRule` or a custom `SecondaryValidation` rule plugin that harnesses its functionality.

Implement PluginSecondaryConstraint:
https://github.com/HicServices/RDMP/blob/develop/Rdmp.Core/Validation/Constraints/Secondary/PluginSecondaryConstraint.cs

This subsystem does not innately support dependency injection so we would need to prime it with config details somehow.

We also need to know the column name (could be a problem for SecondaryConstraint).

**An alternative would be to flip the problem on it's head and create a new `IAtomicCommand` that takes the Catalogue and runs IsIdentifiable on it and stores the results via the output format adapter API in IsIdentifiable into the DQE**

**Comment by tznind** [comment]
Something like this should be pretty doable

```csharp
using Microservices.IsIdentifiable.Options;
using Microservices.IsIdentifiable.Reporting;
using Microservices.IsIdentifiable.Reporting.Reports;
using Microservices.IsIdentifiable.Runners;
using Rdmp.Core.CommandExecution;
using Rdmp.Core.Curation.Data;
using Rdmp.Core.Curation.Data.Defaults;
using Rdmp.Core.DataQualityEngine.Data;
using Rdmp.Core.Repositories;

namespace SmiPlugin
{
    internal class RunIsIdentifiable : BasicCommandExecution
    {
        private readonly Catalogue catalogue;

        public RunIsIdentifiable(IBasicActivateItems activator, Catalogue catalogue) : base(activator)
        {
            this.catalogue = catalogue;
            if(catalogue.TimeCoverage_ExtractionInformation_ID == null)
            {
                SetImpossible("Catalogue must have a time coverage field");
                return;
            }

            if(activator.ServerDefaults.GetDefaultFor(PermissableDefaults.DQE) == null)
            {
                SetImpossible("There is no DataQualityEngine server configured");
                return;
            }
        }

        public override void Execute()
        {
            base.Execute();

        }

        private class IsIdentifiableCatalogueOptions : IsIdentifiableAbstractOptions
        {
            public Catalogue Catalogue { get; }

            public IsIdentifiableCatalogueOptions(Catalogue catalogue)
            {
                Catalogue = catalogue;
            }


            public override string GetTargetName()
            {
                return Catalogue.Name;
            }
        }

        private class IsIdentifiableCatalogueRunner : IsIdentifiableAbstractRunner
        {
            public IsIdentifiableCatalogueRunner(Catalogue c) : base(new IsIdentifiableCatalogueOptions(c))
            {
                Reports.Add(new ToDQEReporter(c));
            }

            public override int Run()
            {
                // TODO fetch data and stream
                return 0;
            }
        }
        internal class ToDQEReporter : IFailureReport
        {
            private Evaluation evaluation;

            public ToDQEReporter(Catalogue catalogue)
            {

                var dqeRepository = new DQERepository(catalogue.CatalogueRepository);

                // TODO this constructor is internal and would need to be public to support this kind of thing
                evaluation = new Evaluation(dqeRepository, catalogue);

            }
            public void Add(Failure failure)
            {
                // TODO update Evaluation
            }

            public void AddDestinations(IsIdentifiableAbstractOptions options)
            {
                
            }

            public void CloseReport()
            {
                // TODO mark Evaluation complete
            }

            public void DoneRows(int numberDone)
            {
                
            }
        }
    }
}


```

**Comment by rkm** [comment]
I'm not overly familiar with RDMP's innards, so I don't really follow the above discussion.

I'll raise a more general point though, which we can move to a separate issue if this gets too off-topic! This repo seems to be becoming quite large and difficult to work with, in terms of both the VS sln size and "things that need to be packaged". Having all these components packaged together means that we need to release and deploy the whole lot even if e.g. we want to change 1 line in the SR python scripts.

Mentioning this here because IsIdentifiable is something which could be available as a CLI tool and consumable library in its own repo, and pulled into the microservices and RDMP as needed.

**Comment by tznind** [comment]
> Mentioning this here because IsIdentifiable is something which could be available as a CLI tool and consumable library in its own repo, and pulled into the microservices and RDMP as needed.

That is how it was originally: https://github.com/HicServices/IsIdentifiable.

It was moved into the SmiServices repo so that it could operate automatically as part of extraction.

**Comment by tznind** [comment]
I have started this here:

https://github.com/HicServices/IsIdentifiable

There will be a NuGet package for running IsIdentifiable which we will need to retro fit the services wrapper back onto and a command line `ii` which runs the reviewer TUI and on demand modes

**Comment by tznind** [comment]
Now being handled on https://github.com/SMI/IsIdentifiable/pull/14
