### ISSUE TITLE
net6.0

### ISSUE THREAD

**Issue by tznind** [SMI/SmiServices#1038]
We should probably move to net6.0 sdk 

Should just be a matter of updating the SDK in CI and in [SmiServices/global.json](https://github.com/SMI/SmiServices/blob/47763734f4d2aafce2137712ff4a690fe16e29c8/global.json#L3)

End of Life for net5 is May of this year (https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core)

net6.0 is LTS so good till November 8, 2024

**Comment by rkm** [comment]
relates to #916
