### ISSUE TITLE
Fix coverage reporting

### ISSUE THREAD

**Issue by rkm** [SMI/SmiServices#1049]
The tool we use for uploading coverage has not been updated to work with .NET 6, and looking at the repo it seems to have been abandoned. https://github.com/csMACnz/coveralls.net

There's hopefully some alternative out there. It's probably not doing too much work though, likely just POST-ing some data to an API, so maybe it's easier long-term to write a small python tool which does this?

For the moment I'm going to disable the coverage task from the CI to unblock our PRs.

**Comment by tznind** [comment]
This is how I did code coverage the last time I had to add it to a repo:

https://github.com/gui-cs/TerminalGuiDesigner/blob/d49f1991642d925f5d0ddc5452a0e4232ca445f8/.github/workflows/build.yml#L20-L30

It updates a gist: https://gist.github.com/tznind/2a31eee1c9151917aa8d17b59bc86633 every time you run CI 

The markdown to display it is:

```
![Code Coverage](https://img.shields.io/endpoint?url=https://gist.githubusercontent.com/tznind/2a31eee1c9151917aa8d17b59bc86633/raw/code-coverage.json)
```
Advantages:
- Its very lightweight
- Its all GitHub all the time (i.e. no third party coverage hosting)

Disadvantages:
- Coverage is only shown on the CI build output for PRs (i.e. no review checks)
- If you don't restrict which branches the update run on the badge will track the last successful run not `main` branch
