### ISSUE TITLE
Update instructions on building SmiServices

### ISSUE THREAD

**Issue by karacolada** [SMI/SmiServices#1490]
The [section on building the Java projects](https://github.com/SMI/SmiServices#building-the-java-projects) in the root README of the project is out of date. The mentioned files were removed in March 2022 in commit 6cb80486c1883abcb4858af8eaa22dd107262fec. Java is only required for running CTP at the moment, i.e. at the extraction stage.

Good places to check for updated steps:
- [GitHub Actions for CTP](https://github.com/SMI/SmiServices/blob/master/.github/workflows/main.yml#L134)
- [`bin/ctp`](https://github.com/SMI/SmiServices/tree/596d9e4d74b49c813202e7cd6577aba163908dc2/bin/ctp)

**Comment by rkm** [comment]
Thanks for checking this. Would you like to contribute a PR to update the instructions?

**Comment by karacolada** [comment]
Sure! Haven't tested the resources linked above, but once I do, I'll update the docs in a PR.
