### ISSUE TITLE
[feature] generate linkage CSV of UIDs to FilePath for extractions

### ISSUE THREAD

**Issue by rkm** [SMI/SmiServices#1842]
We have received a request to create a CSV file which links DICOM UIDs to the output FilePath to improve the ease of creating downstream scripts.

This should be a simple CSV with header `StudyInstanceUID,SeriesInstanceUID,SOPInstanceUID,FilePath`

**Comment by jas88** [comment]
I have a tool for this called `DicomAudit` which matches that with a different order and the addition of `Modality`.

**Comment by jas88** [comment]
I'd already used `dsm2csv` for the SR ICD11 extraction tool, but they have a fair bit in common - maybe I'll merge the two under that name and retire the `DicomAudit` one.

**Comment by rkm** [comment]
I don't think we need this anymore, as we no longer modify the UID values in the output paths (by removing leading dots)
