### ISSUE TITLE
Allow file extraction to be started directly from database table

### ISSUE THREAD

**Issue by rkm** [SMI/SmiServices#1922]
It would be useful to have the ability to start an extraction job given from a database table which contains a list of extraction identifiers (e.g., SeriesInstanceUIDs)

**Comment by jas88** [comment]
Should we read the column directly, or just accept a CSV of IDs dumped by the DB client for simplicity?

**Comment by howff** [comment]
Or allow the actual SQL query to be specified directly, for maximum flexibility?

**Comment by jas88** [comment]
@howff That could work, but we do have command line SQL clients for doing that already, why reinvent the wheel/pipe?

mysqlcient 'SELECT SeriesInstanceUID FROM CT_SeriesTable WHERE ...' --tabbed -Usmi smi_images | tee project32-extraction1.csv | ./smi fetch-by-id --id=series --modality=CT
