### ISSUE TITLE
Unknown output in IsIdentifiable service

### ISSUE THREAD

**Issue by rkm** [SMI/SmiServices#398]
Unsure if this is anything to worry about, as the service still appears to function properly.

```console
> dotnet $SMI_ROOT/SmiServices/IsIdentifiable.dll service -y ~/nfs_home/extraction-testing/extraction_config_test.yaml --rulesdirectory $SMI_ROOT/data/IsIdentifiableRules
Bootstrapper -> Main called, constructing host
2020-09-18 12:58:43.5238| INFO|IsIdentifiableHost|Host logger created with SMI logging config||
...
2020-09-18 12:58:45.4067| INFO|Microservices.IsIdentifiable.Runners.IsIdentifiableAbstractRunner|Loading Rules Yaml||
Error in pixReadMemTiff: function not present
Error in pixReadMem: tiff: no pix returned
Error in pixaGenerateFontFromString: pix not made
Error in bmfCreate: font pixa not made
2020-09-18 12:58:46.2038| INFO|Smi.Common.Helpers.MicroserviceObjectFactory|Successfully constructed Type 'Microservices.IsIdentifiable.Service.TesseractStanfordDicomFileClassifier'||
Bootstrapper -> Host constructed, starting aux connections
Bootstrapper -> Host aux connections started, calling Start()
Bootstrapper -> Host created and started...
MicroserviceHostBootstrapper exiting. Service will exit when consumer threads are joined
Empty page!!
Empty page!!
Empty page!!
Empty page!!
Empty page!!
Empty page!!
Error in pixWriteMemPng: function not present
Error in pixWriteMemPng: function not present
...
Empty page!!
Empty page!!
Empty page!!
Empty page!!
Empty page!!
Empty page!!
^C2020-09-18 13:00:52.3781| INFO|IsIdentifiableHost|Host Stop called: Ctrl+C pressed||
2020-09-18 13:00:52.8402| INFO|IsIdentifiableHost|Host stop completed||
ObjectCache(0x7fd0c5ecb720)::~ObjectCache(): WARNING! LEAK! object 0x2874d70 still has count 1 (id /nfs/smi/home/smi/data/tessdata/eng.traineddatalstm-punc-dawg)
ObjectCache(0x7fd0c5ecb720)::~ObjectCache(): WARNING! LEAK! object 0x292d490 still has count 1 (id /nfs/smi/home/smi/data/tessdata/eng.traineddatalstm-word-dawg)
ObjectCache(0x7fd0c5ecb720)::~ObjectCache(): WARNING! LEAK! object 0x292d540 still has count 1 (id /nfs/smi/home/smi/data/tessdata/eng.traineddatalstm-number-dawg)
```

Edit: Further output

```console
...
Detected 26 diacritics
```

**Comment by tznind** [comment]
Empty page is familiar think I remember seeing that before.  Think its something from tesseract.

Looks similar to: https://github.com/tesseract-ocr/tesseract/issues/2717

Could be some images in dicoms are in a format not supported out of the box by tesseract

**Comment by rkm** [comment]
If that's the case then I'm wondering if we're not properly scanning some images but reporting "all ok". Probably merits a deeper investigation.

We should check if updating the libs we've cached [here](https://github.com/SMI/SmiServices/tree/master/lib) will help.

Also these errors are printed to stdout rather than to the log stream, so will only be seen and recorded if you run the service with a console attached.

**Comment by howff** [comment]
I think the messages are always printed, regardless of input images, so they don't indicate a problem during processing. Some simply mean that the library was built without certain features. It doesn't prevent our dicom images from being processed since they are internally converted to bitmaps anyway. For that reason I didn't look too hard into why the messages go to stdout or how to stop them.

**Comment by tznind** [comment]
Yes that's a good point @howff  I had forgotten that we already read the images in C# and fed as Bitmap.

**Comment by tznind** [comment]
Closing because consensus is that this is a non issue.
