### ISSUE TITLE
File paths for identifiable extractions still end in "-an.dcm"

### ISSUE THREAD

**Issue by rkm** [SMI/SmiServices#403]

**Comment by tznind** [comment]
This is controlled by `ProjectPathResolverType`.  See `DefaultProjectPathResolver` which is an `IProjectPathResolver`.

If you want to add a different subdirectory structure or file naming strategy just inherit IProjectPathResolver for a new implementation (or inherit from DefaultProjectPathResolver).  For example a new one could be `NoSuffixProjectPathResolver`.  Then you just put the Type name in the config (full name) and it should use the new class.

I can create a PR for this if you want?

**Comment by rkm** [comment]
Sure, that would be great thanks. I've noticed a couple other issues which I'm working on in the `extraction-fixes` branch, but this seems pretty self-contained.

**Comment by tznind** [comment]
Closing since PR is merged
