### ISSUE TITLE
Generate dependabot upstream package bump entries for the CHANGELOG automatically

### ISSUE THREAD

**Issue by rkm** [SMI/SmiServices#477]
It would be useful to include a list of dependabot package updates in the CHANGELOG for each release, e.g. `bump foo from x to y`.

These could be manually added in each dependabot PR which is opened, since it needs a review anyway. We should work smarter not harder though, as this is something that could easily be generated during the release process by a script! (maybe something exists already?)

**Comment by tznind** [comment]
This has been solved by the 'news' system

**Comment by rkm** [comment]
The news files don't generate package updates at the moment

**Comment by tznind** [comment]
I thought that's what the python script did?

**Comment by rkm** [comment]
This is now automatically included on the Release page for each version
