### ISSUE TITLE
Regression/unit testing of Python scripts

### ISSUE THREAD

**Issue by jas88** [SMI/SmiServices#503]
- Need to add testing for the supporting scripts, including the ones added by PR #501
- Maybe refactor/update some of the other testing bits when replacing Travis - discuss best strategy for this in January?

**Comment by rkm** [comment]
Stop reading my mind!

**Comment by rkm** [comment]
Some other things we may want to look into after reviewing #502

-   building packaged wheel(s) that we can easily deploy (so we don't have to mess with any `sys.path` nonsense) into virtualenvs
-   pulling-out inline data and options into config files
-   code linters / formatters (also needed for c# codebase)

**Comment by howff** [comment]
The Python code can now be packaged and tested in the Azure pipeline, so maybe this issue has been resolved by PR #654
