### ISSUE TITLE
Randomise exchange/queue names in MicroserviceTester

### ISSUE THREAD

**Issue by rkm** [SMI/SmiServices#515]
Currently if multiple tests are run in parallel we may experience strange / flaky test behaviour since multiple test cases may use the same exchange and queue names.

**Comment by tznind** [comment]
In my opinion tests should not run in parallel when communicating with RabbitMQ, that just sounds like a recipy for disaster.  The same way we don't want to run database tests in parallel.

Can we close this? @rkm

**Comment by rkm** [comment]
I think we shouldn't needlessly restrict ourselves to running the lengthy test suite in serial - the full test set takes about 15m currently. One solution could be to use a separate random vhost for each test to ensure isolation. Optimising this would reduce the time spent waiting for CI, and make it much easier for developers to run things locally and get quick feedback on changes.

There's possibly another solution here though, which is to not repeatedly test the same thing in every test. We could have one small test project which tests actually publishing/receiving messages from rabbtimq, and use mocks or other abstractions in all other cases. Full integration testing like we do currently is probably more suited for the QA environment.
