### ISSUE TITLE
Test project for IsIdentifiableReviewer

### ISSUE THREAD

**Issue by rkm** [SMI/SmiServices#553]
Not sure if there's much to test since this is a GUI/TUI application, but it looks like we're missing a test project for this

**Comment by tznind** [comment]
They are mostly in IsIdentifiable.Tests project

https://github.com/SMI/SmiServices/blob/3ec8488f4ab70268bae73d008e14c058d9b1e87f/tests/microservices/Microservices.IsIdentifiable.Tests/Microservices.IsIdentifiable.Tests.csproj#L24-L26

**Comment by rkm** [comment]
Ah I thought that might be the case. It's a minor thing, but I think it's worthwhile to have them logically separated. Happy to do this myself of course!
