### ISSUE TITLE
CTPanonymiser uses 100% CPU when doing nothing

### ISSUE THREAD

**Issue by howff** [SMI/SmiServices#61]
In my personal VM (admittedly slightly different environment to NSH and hosted by vmware) the java processes were observed to be using 100% CPU. A quick look with strace suggested it could be polling?

**Comment by rkm** [comment]
Investigating!

**Comment by rkm** [comment]
I can reproduce this on a local CentOS VM. Will need to investigate further in January.

**Comment by rkm** [comment]
I ran `java -Xrunhprof:cpu=samples,file=ctp.hprof -jar CTPAnonymiser-portable-1.0.0.jar ... ` which produced a file with the following:

```
...
CPU SAMPLES BEGIN (total = 2989) Fri Dec 20 10:34:58 2019
rank   self  accum   count trace method
   1 65.51% 65.51%    1958 300585 java.net.SocketInputStream.socketRead0
   2 32.39% 97.89%     968 300697 org.smi.common.rabbitMq.RabbitMqAdapter$ConsumeRunnable.run
   3  0.23% 98.13%       7 300073 java.lang.ClassLoader.defineClass1
   4  0.10% 98.23%       3 300053 java.util.zip.Inflater.inflateBytes
   5  0.10% 98.33%       3 300615 java.net.Inet6AddressImpl.lookupAllHostAddr
   6  0.07% 98.39%       2 300078 java.lang.ClassLoader.findBootstrapClass
   7  0.07% 98.46%       2 300079 java.lang.Object.getClass
   8  0.03% 98.49%       1 300020 java.util.zip.ZipFile.<init>
   9  0.03% 98.53%       1 300080 java.lang.Class.getDeclaredMethods0
  10  0.03% 98.56%       1 300113 sun.misc.URLClassPath$JarLoader.getResource
...
```

Looks like a good place to start debugging, but I don't have any more time for now 😞

**Comment by jas88** [comment]
The 2nd item there should be addressed by my refactoring PR - the RabbitMQ Adapter had a thread spinning. (1st should be a measurement artefact AIUI: socketRead0 is the thread *waiting* for messages back from RabbitMQ, which shouldn't be eating any CPU, but spends all the inactive time.)
