### ISSUE TITLE
Separate application code into re-usable lib projects

### ISSUE THREAD

**Issue by rkm** [SMI/SmiServices#633]
From #631:
> The second issue is caused by some projects for applications or services relying on code from another application or service, and separate copies of each being built. I think the sensible thing to do here is to pull-out the common classes to another Smi.Common.* project that can be referenced. There would then only be one copy of each in the final output. I also have this as a WIP, although not pushed yet.

While that particular reason is no longer valid, it might still be a good idea to separate the re-used code in order to decouple the code and simplify our tests.

**Comment by tznind** [comment]
This ticket seems very broad and vague.  What re-used code do you want to seperate out @rkm? We already have `Smi.Common` and refactored to use `SmiRunner`.  Is there a large part of the codebase you want to move to a new project?  If so can you please either list the bits of code that should be moved to `Smi.Common` (or a new csproj) or close this ticket.

**Comment by rkm** [comment]
Specifically the `IsIdentifiable` csproj contains a lot of code which is used by other apps e.g. the reviewer and CohortPackager. Some of the IdentifierMapper classes are also used in TriggerUpdates, but that's probably ok.
