### ISSUE TITLE
Improve Azure Pipelines documentation

### ISSUE THREAD

**Issue by rkm** [SMI/SmiServices#663]
We have a general top-level [README](https://github.com/SMI/SmiServices/tree/master/.azure-pipelines) for this. We could improve our docs though by adding:

-   A README in each sub-dir with documentation for its contents
-   In-line explanations for various bits of syntax
-   ...

**Comment by rkm** [comment]
@howff could you add your thoughts on this please?

**Comment by howff** [comment]
Is there a desire to run it locally?  Either for running the tests or for building and packaging.
Maybe you can run buildArtefacts manually, or does it need the whole agent?
https://docs.microsoft.com/en-gb/azure/devops/pipelines/agents/v2-linux?view=azure-devops

**Comment by rkm** [comment]
Some of the general scripts may be useful outside of the AP build, so I can move them out of the `.azure-pipelines` directory. The buildArtefacts script should already work manually, but I'll check the others and add some documentation.

You mentioned [syntax oddities](https://github.com/SMI/SmiServices/pull/654#pullrequestreview-609568719) - if you point me to specific instances then I can add some docs / comments.
