### ISSUE TITLE
IsIdentifiableReviewer button DigitsOnly acts like AllCharacters

### ISSUE THREAD

**Issue by howff** [SMI/SmiServices#671]
Pressing the `[ \d ]` button should convert digits only into a regex `[\d]+`
but actually converts everything as seen in the screenshots:
![IsIdentifiableReviewer DigitsOnly before](https://user-images.githubusercontent.com/3064316/111175593-7dfe2000-85a0-11eb-9f44-85b7fbd34318.PNG)
![IsIdentifiableReviewer DigitsOnly after](https://user-images.githubusercontent.com/3064316/111175604-8191a700-85a0-11eb-9c8d-70e004b9d9ce.PNG)

**Comment by tznind** [comment]
Ok I can replicate this only when the failure `HasOverlappingParts`.  That is where IsIdentifiable found 2+ Words in the input 

For example in the store report that you open you have

```
FunBooks.HappyOzz,1.2.3,Narrative,This has 0verlapping Fa1lures,0verlapping###0verlapping Fa1lures,Person###Date,9###9
```

In this case one rule identifies `Overlapping` as person and another identifies `Overlapping Failures` as a date.  You can get overlapping failures without the same start too e.g. matching `11-11-2001` and `-11-`

In these cases `G` and `\d` (and also `\c` and `\d\c`) all behave differently ...

I guess the best way to handle that would be to conflate all the overlaps and generate a pattern after doing that

**Comment by howff** [comment]
I must have misunderstood because I assumed it was operating on a lower level and simply did a naive string replacement, eg.  full pattern `^My Hospital 11-11-2001 Brain$` press `\d` to replace each digit with a `\d` giving `^My Hospital \d\d-\d\d-\d\d\d\d Brain$`

**Comment by tznind** [comment]
Ah no it will match the failing part e.g. 

```
Ahoy Dr Spock123
```
would generate a pattern

```
(Dr Spock\d\d\d)$
```

It detects that the bad bit `Dr Spock123` appears at the end of the string so adds in a $ and it doesn't care about what comes before the failing part.

**Comment by tznind** [comment]
If put in a fix that conflates overlapping matches so that should fix this issue.  Fix is in feature/reviewer-improvs.  PR inc today or tomorrow.
