### ISSUE TITLE
ImageType is null for 92% of SR images and so get rejected at extraction time

### ISSUE THREAD

**Issue by tznind** [SMI/SmiServices#687]
```
When you tested extraction of SRs did you get them out ok? I am worried about the 92% of ImageType nulls in the table since that should be resulting in rejections.  How many SRs have you tested and how many got rejected?

> I tried 6 SRs and 5 were rejected.
```

might need to write some code to apply different rejectors per modality or override default for SR.  The only other way would be to set the ImageType to ORIGINAL\PRIMARY where it is null in SR and that's probably the wrong way to go (better to edit code than data).

I don't think that we should just green light all empty ImageType fields since CT/MR probably shouldn't be extracted blindly where ImageType is null.

It would be nice if we could just add r["Modality"] == 'SR' into the DynamicRules.txt but most image tables don't have that field and the rules are run on all tables that are extracted from so would crash.

See more here about checking for columns:
https://stackoverflow.com/questions/3599861/how-can-i-determine-if-the-column-name-exist-in-the-resultset

**Comment by tznind** [comment]
A sensible first step would be to add:

```
if (string.IsNullOrWhitespace(row["ImageType"].ToString()))
{
    return "ImageType is null";
}
```

This will help us distinguish between legit SECONDARY images and cases where it is missing.  Also it will let us detect this problem in any other datasets where it might manifest.

**Comment by howff** [comment]
Tested the same SR extraction again and the PR has fixed this issue
