### ISSUE TITLE
Enable nullable types

### ISSUE THREAD

**Issue by rkm** [SMI/SmiServices#719]
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-value-types

Had a look at this a while back and there's a decent amount of work involved. Definitely beneficial in the long-run though.

**Comment by jas88** [comment]
Good plan. It's possible to enable file by file (#nullable enable) to get this started, or per directory via directory.build.props, so at least we don't have to get it done all at once...
