### ISSUE TITLE
Generalise image ingest details

### ISSUE THREAD

**Issue by rkm** [SMI/SmiServices#804]
- Directory scan messages refer to `NationalPACSAccessionNumber`, when this isn't always relevant
- MongoDB document header also contains this. Is it used at all?

**Comment by tznind** [comment]
We made it optional since HIC doesn't store using that layout.  But I think we can axe it completely as you say.  I'm not aware of anything that uses it.

**Comment by tznind** [comment]
Here is how we currently handle reading or not reading Accession number from disk

https://github.com/SMI/SmiServices/blob/fbb09556bcd297b16a24fd35879b5a8c6dcd3165/src/applications/Applications.DicomDirectoryProcessor/Execution/DicomDirectoryProcessorHost.cs#L30-L84
