### ISSUE TITLE
Fixup or remove check for writeable source files during anonymisation

### ISSUE THREAD

**Issue by rkm** [SMI/SmiServices#836]
https://github.com/SMI/SmiServices/blob/abef4abf09c26164d0b3be12fef0ef6084ad42ce/src/microservices/com.smi.microservices.ctpanonymiser/src/main/java/org/smi/ctpanonymiser/execution/SmiCtpProcessor.java#L78-L86

The original check was in place to ensure that source files were not accidentally clobbered by CTP during the anonymisation process, since CTP has the option to overwrite the input file.

This seems like a sensible check to have in place, though not applicable in all situations. Adding a config option which can turn this on/off seems sensible?

**Comment by jas88** [comment]
Making it optional sounds sensible - does the user account the Anonyiser runs as actually have write access to that area of BeeGFS? Does it still run as root and access data on Lustre per the comment, or is that comment out of date?

**Comment by rkm** [comment]
I took a second look at the whole anonymisation process, and it looks like we take a defensive copy of the input file to `tmp_foo.dcm` which is what we actually call the anon method on.

The original copy of the PACS archive on the old Lustre system were world-writeable, which explains why the script was written this way. The current file extract on BeeGFS has correct permissions though, meaning we don't have to run the anonymiser as root(!). Considering that, I think we can re-add the `inFile.canWrite()` check and remove the temporary copy. This would also solve another bug where the temp file isn't cleaned up during a crash, causing the next service which tries to process it to also crash!
