### ISSUE TITLE
Simplify version bumping with MinVer

### ISSUE THREAD

**Issue by tznind** [SMI/SmiServices#858]
If we delete the version number from the header of our our [README](https://github.com/SMI/SmiServices/blob/master/README.md) and add [MinVer](https://github.com/adamralph/minver) then I think we can do away with most of the manual steps in bumping up for release

**Comment by rkm** [comment]
Looks interesting! I had seen the Nerdbank GitVersioning tool before, but this looks like a simplified approach.

+1

**Comment by rkm** [comment]
Closing as we aren't taking this forward for the moment
