### ISSUE TITLE
Add check-config command to CLI

### ISSUE THREAD

**Issue by tznind** [SMI/SmiServices#945]
@rkm rkm 1 hour ago

What might be useful is a script which you can run after setting everything up which verifies all the specified services and databases etc. are reachable?

e.g. something like `./smi check-config -y foo.yaml`

**Comment by rkm** [comment]
Just thinking that this could have 2 modes -- one which just checks the config is load-able (e.g. by constructing a `GlobalOptions` object), and another which actually verifies all the specified services are reachable.
