### ISSUE TITLE
CI failure with  System.Drawing.Common upgrade

### ISSUE THREAD

**Issue by rkm** [SMI/SmiServices#961]
Failure in #959 with System.Drawing.Common upgrade:

```
System.PlatformNotSupportedException: System.Drawing.Common is not supported on non-Windows platforms. See https://aka.ms/systemdrawingnonwindows for more information
```

**Comment by tznind** [comment]
> we have redirected numerous issues to libgdiplus that never got fixed. In comparison, other external dependencies we have taken, such as icu or openssl, are high-quality libraries. It's not viable to get libgdiplus to the point where its feature set and quality is on par with the rest of the .NET stack.

Sounds like some drama.  What an abrupt change to drop support for an OS like that.  Guess we are either sticking to 5.x or doing a bunch of work to migrate to the other packages mentioned.

**Comment by rkm** [comment]
Seems like this won't be a huge issue until we update to .NET 6

**Comment by tznind** [comment]
I have removed the dependency from RDMP in https://github.com/HicServices/RDMP/pull/667.  It doesn't look like it affects anything.

Looks like it crept in with resource handling (resx files) probably via the winforms designer.  I guess that as dotnet standard was beefed up to cover more libraries the `System.Drawing` namespace took over whatever temporary thing they had going with `System.Drawing.Common`

**Comment by tznind** [comment]
In fact here we go https://stackoverflow.com/questions/54180326/net-core-unable-to-use-bitmap the old guidance was Bitmap isn't implemented yet use `System.Drawing.Common` hah.

**Comment by tznind** [comment]
Bit confusing actually [Bitmap](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.bitmap?view=dotnet-plat-ext-6.0) class is in namespace `System.Drawing` but it lists its assembly as `Bitmap.Drawing.Common`... so its possible that removing the nuget reference doesn't help and that that class is now supported via the main SDK rather than the NuGet package and therfore we will still see the issue.

**Comment by rkm** [comment]
Just checked locally, and simply removing it does seem to let the build succeed. It may still fail in the tests though if it loads anything via reflection.

I'll open a PR to remove it and we'll see what happens I guess.
