### ISSUE TITLE
Python unit test regression

### ISSUE THREAD

**Issue by jas88** [SMI/SmiServices#977]
Recent PR with no Python changes hit this failure in Dicom.py:

ImportError: cannot import name 'Mapping' from 'collections' (C:\hostedtoolcache\windows\Python\3.10.0\x64\lib\collections\__init__.py)

Apparently this is something Python broke between 3.9 and 3.10.

**Comment by rkm** [comment]
think it's because the default python version used in the CI was updated. We should pin it to 3.6 since that's the version we have in the NSH currently.

**Comment by jas88** [comment]
Longer term we need to update the NSH stack somehow, but pinning sounds OK for now.

There's no Python in the HIC install yet (the NLP stuff is still a TODO after "get the SQL Server connection working"!) so at least there's no conflict there...

**Comment by tznind** [comment]
![image](https://user-images.githubusercontent.com/31306100/145771568-b3db4e44-111a-4a4f-86d0-feee6f13efbc.png)

**Comment by rkm** [comment]
On second look, `from collections import Mapping` is marked as deprecated since python 3.3 and finally removed in 3.10 (which is why we're seeing this error now). So the correct fix is to use the correct import.

I think there's still value in pinning the CI python version to 3.6 for the moment though.

**Comment by rkm** [comment]
Oh - we already implemented the python version pinning in #931 but looks like these changes weren't included in @jas88 's patch for #976? So nothing to do there.

The PR for the import fix is open though.
